# Settings
wandb: True
seed: 0

# Dataset
name: "LJSPEECH"
frame_len: 2.0
SR: 22050
batched: False
batch_size: 64
samples: 5

# Train
mode: "nerf"
network: [128]
epochs: 101
bias: True
L: 32
lr: 0.001
optimizer: "Adam"
loss_fn: "MSELoss"
loss_lst: ["L1Loss", "HuberLoss", "SmoothL1Loss"]
SNR: True
LSD: False

# Output
log_img: 50
plot: False